//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datagrid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public string PolicyNo { get; set; }
        public System.Guid GlobalEntityID { get; set; }
        public Nullable<System.Guid> ResponsibleEntityID { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
        public string BouquetPrefix { get; set; }
        public string CountryID { get; set; }
        public string MerchCode { get; set; }
        public string OfficeCode { get; set; }
        public int ProductCycle { get; set; }
        public string LUCPolicyStatus { get; set; }
        public int DebitRunID { get; set; }
        public Nullable<int> YearWeekID { get; set; }
        public Nullable<int> FailureCount { get; set; }
        public string PolicyXML { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public Nullable<System.Guid> InsertedBy { get; set; }
        public string InsertedByName { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<int> LegacyProductCycle { get; set; }
        public Nullable<int> LegacyPolicyStatus { get; set; }
        public Nullable<int> LegacyMerchandiserCodeID { get; set; }
        public string SupervisorCode { get; set; }
        public string TeamLeaderCode { get; set; }
        public Nullable<System.Guid> GenisysID { get; set; }
        public string LUCPaymentMethod { get; set; }
        public string LUCBillingCycle { get; set; }
        public string ParentSalesChannelID { get; set; }
        public string SalesChannelID { get; set; }
        public string campaignID { get; set; }
        public Nullable<bool> IsFixedExtractDate { get; set; }
        public Nullable<bool> IsMerchPayable { get; set; }
        public Nullable<bool> IsPostponeActivation { get; set; }
        public Nullable<System.DateTime> PolicyCommencementDate { get; set; }
    
        public virtual GlobalEntity GlobalEntity { get; set; }
        public virtual GlobalEntity GlobalEntity1 { get; set; }
    }
}
